[build]
  publish = "."

[[headers]]
  for = "/vendor/occt-import-js.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/vendor/libs/draco/gltf/draco_decoder.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/vendor/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/vendor/replicad_single.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=604800"
